-- ==============================================
-- AI PRICING ENTERPRISE LAYERS - DATABASE SCHEMA
-- ==============================================

-- 1. PROPERTY PROFILE TABLE (Property Context Layer)
-- Stores property-specific characteristics for scaling recommendations
CREATE TABLE public.property_pricing_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id TEXT NOT NULL UNIQUE,
  property_name TEXT,
  
  -- Capacity info
  rooms_count INTEGER DEFAULT 0,
  
  -- Historical metrics (updated automatically)
  avg_occupancy_90d NUMERIC(5,2) DEFAULT 0,
  avg_adr_90d NUMERIC(12,2) DEFAULT 0,
  avg_velocity_90d NUMERIC(8,4) DEFAULT 0,
  
  -- Volatility score (0-1): how much demand fluctuates
  volatility_score NUMERIC(4,3) DEFAULT 0.5,
  
  -- OTA mix ratio (0-1): proportion of OTA bookings vs direct
  ota_mix_ratio NUMERIC(4,3) DEFAULT 0.8,
  
  -- Pricing intent (configurable per property)
  pricing_intent TEXT DEFAULT 'BALANCED' CHECK (pricing_intent IN ('MAX_REVENUE', 'MAX_OCCUPANCY', 'BALANCED')),
  
  -- Seasonality config
  peak_months INTEGER[] DEFAULT '{}',
  low_months INTEGER[] DEFAULT '{}',
  
  -- Audit
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.property_pricing_profiles ENABLE ROW LEVEL SECURITY;

-- RLS policies (allow read for authenticated users)
CREATE POLICY "Anyone can view property pricing profiles"
  ON public.property_pricing_profiles FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can manage property pricing profiles"
  ON public.property_pricing_profiles FOR ALL
  USING (auth.uid() IS NOT NULL);

-- 2. CALENDAR CONTEXT TABLE (Temporal Context Layer)
-- Stores special dates: weekends, holidays, events, peak periods
CREATE TABLE public.pricing_calendar_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id TEXT, -- NULL = applies to all properties
  event_date DATE NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('NORMAL', 'WEEKEND', 'PEAK', 'EVENT', 'LOW')),
  event_name TEXT, -- e.g., "Tết Nguyên Đán", "Formula 1"
  price_weight NUMERIC(4,2) DEFAULT 1.0, -- multiplier for pricing decisions
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID REFERENCES auth.users(id),
  
  UNIQUE(property_id, event_date)
);

-- Enable RLS
ALTER TABLE public.pricing_calendar_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view calendar events"
  ON public.pricing_calendar_events FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can manage calendar events"
  ON public.pricing_calendar_events FOR ALL
  USING (auth.uid() IS NOT NULL);

-- 3. AI RECOMMENDATION LOG TABLE (For Post-Decision Review)
-- Logs each recommendation generated by AI
CREATE TABLE public.ai_pricing_recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id TEXT NOT NULL,
  room_type_id TEXT,
  
  -- Date range
  date_from DATE NOT NULL,
  date_to DATE NOT NULL,
  
  -- Recommendation details
  action TEXT NOT NULL CHECK (action IN ('INCREASE', 'DECREASE', 'HOLD', 'WATCH')),
  action_strength TEXT CHECK (action_strength IN ('LIGHT', 'MODERATE', 'STRONG')),
  priority TEXT CHECK (priority IN ('IMMEDIATE', 'WATCH', 'OPTIONAL')),
  confidence NUMERIC(4,3) NOT NULL, -- 0-1
  
  -- Context at time of recommendation
  signal_class TEXT,
  velocity_at_time NUMERIC(8,4),
  baseline_velocity NUMERIC(8,4),
  occupancy_at_time NUMERIC(5,2),
  remaining_inventory INTEGER,
  days_to_checkin INTEGER,
  
  -- Humility layer data
  data_confidence NUMERIC(4,3) NOT NULL,
  silence_reason TEXT, -- NULL if recommendation was made, otherwise reason for silence
  
  -- Context layers applied
  property_context JSONB, -- snapshot of property profile used
  temporal_context JSONB, -- calendar context applied
  business_intent TEXT,
  
  -- Explanation
  explanation_text TEXT,
  why_not_reasons JSONB,
  
  -- Validity
  validity_window_hours INTEGER DEFAULT 24,
  expires_at TIMESTAMPTZ,
  
  -- Audit
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.ai_pricing_recommendations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view AI recommendations"
  ON public.ai_pricing_recommendations FOR SELECT
  USING (true);

CREATE POLICY "System can insert AI recommendations"
  ON public.ai_pricing_recommendations FOR INSERT
  WITH CHECK (true);

-- Index for querying recommendations
CREATE INDEX idx_ai_recommendations_property_date 
  ON public.ai_pricing_recommendations(property_id, date_from);

-- 4. DECISION OUTCOME TABLE (Post-Decision Review)
-- Tracks what happened after each recommendation
CREATE TABLE public.ai_pricing_decision_outcomes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recommendation_id UUID NOT NULL REFERENCES public.ai_pricing_recommendations(id) ON DELETE CASCADE,
  
  -- User action
  user_action TEXT NOT NULL CHECK (user_action IN ('FOLLOWED', 'IGNORED', 'MODIFIED', 'PENDING')),
  user_action_at TIMESTAMPTZ,
  user_id UUID REFERENCES auth.users(id),
  user_note TEXT,
  
  -- Price change made (if any)
  price_before NUMERIC(12,2),
  price_after NUMERIC(12,2),
  price_change_pct NUMERIC(6,2),
  
  -- Outcome (evaluated after validity window)
  outcome TEXT CHECK (outcome IN ('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'PENDING')),
  outcome_evaluated_at TIMESTAMPTZ,
  
  -- Metrics at evaluation time
  final_occupancy NUMERIC(5,2),
  final_remaining_inventory INTEGER,
  bookings_received INTEGER DEFAULT 0,
  revenue_impact_estimate NUMERIC(12,2),
  
  -- Outcome details
  outcome_explanation TEXT,
  outcome_score NUMERIC(4,2), -- -1 to +1 score for model training
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.ai_pricing_decision_outcomes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view decision outcomes"
  ON public.ai_pricing_decision_outcomes FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can manage decision outcomes"
  ON public.ai_pricing_decision_outcomes FOR ALL
  USING (auth.uid() IS NOT NULL);

-- Index for querying outcomes
CREATE INDEX idx_decision_outcomes_recommendation 
  ON public.ai_pricing_decision_outcomes(recommendation_id);

-- 5. LONG-TERM BASELINE ANCHOR TABLE (Anti-Drift Guardrail)
-- Stores quarterly/seasonal baselines to prevent price drift
CREATE TABLE public.ai_pricing_baseline_anchors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  property_id TEXT NOT NULL,
  room_type_id TEXT,
  
  -- Period
  anchor_type TEXT NOT NULL CHECK (anchor_type IN ('QUARTER', 'SEASON', 'YEAR')),
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  
  -- Baseline metrics
  avg_rate NUMERIC(12,2) NOT NULL,
  avg_occupancy NUMERIC(5,2) NOT NULL,
  avg_velocity NUMERIC(8,4) NOT NULL,
  avg_adr NUMERIC(12,2),
  revpar NUMERIC(12,2),
  
  -- For comparison
  min_rate NUMERIC(12,2),
  max_rate NUMERIC(12,2),
  rate_std_dev NUMERIC(12,2),
  
  -- Validity
  is_active BOOLEAN DEFAULT true,
  confidence NUMERIC(4,3) DEFAULT 0.5,
  sample_size INTEGER DEFAULT 0,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  
  UNIQUE(property_id, room_type_id, anchor_type, period_start)
);

-- Enable RLS
ALTER TABLE public.ai_pricing_baseline_anchors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view baseline anchors"
  ON public.ai_pricing_baseline_anchors FOR SELECT
  USING (true);

CREATE POLICY "System can manage baseline anchors"
  ON public.ai_pricing_baseline_anchors FOR ALL
  USING (auth.uid() IS NOT NULL);

-- 6. Trigger to update updated_at
CREATE TRIGGER update_property_pricing_profiles_updated_at
  BEFORE UPDATE ON public.property_pricing_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_decision_outcomes_updated_at
  BEFORE UPDATE ON public.ai_pricing_decision_outcomes
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_baseline_anchors_updated_at
  BEFORE UPDATE ON public.ai_pricing_baseline_anchors
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();