/**
 * SEND-PUSH EDGE FUNCTION - PRODUCTION FIX
 *
 * Handles sending Web Push notifications with:
 * - FIXED VAPID JWT signing for iOS Safari/APNs
 * - Comprehensive per-subscription logging
 * - Auto-clean for 404/410 expired subscriptions
 * - Detailed failures[] array for debugging
 * - Retry logic for 429/5xx
 *
 * Security: Service role only (internal calls)
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// ============================================
// TYPES
// ============================================

type EventType =
  | "BOOKING_NEW"
  | "BOOKING_MODIFIED"
  | "BOOKING_CANCELLED"
  | "MESSAGE_INBOUND"
  | "PUSH_TEST";

interface SendPushRequest {
  event_type: EventType;
  idempotency_key: string;
  recipient_user_ids?: string[];
  assigned_to_user_id?: string;
  use_triage_group?: boolean;
  broadcast_all?: boolean;
  payload: {
    title: string;
    body: string;
    icon?: string;
    badge?: string;
    tag?: string;
    deep_link?: string;
    entity_id?: string;
    data?: Record<string, unknown>;
  };
  source_table?: string;
  source_record_id?: string;
  debug?: boolean;
}

interface PushSubscription {
  user_id: string;
  subscription_id: string;
  endpoint: string;
  p256dh: string;
  auth: string;
}

// Per-subscription failure detail for API response
interface FailureDetail {
  endpointShort: string;
  userId: string;
  statusCode: number | null;
  reason: string;
  bodySnippet: string | null;
  timestamp: string;
}

interface PushSendResult {
  success: boolean;
  statusCode?: number;
  error?: string;
  errorBody?: string;
  needResubscribe?: boolean;
  vapidMismatch?: boolean;
  badRequest?: boolean;
  payloadTooLarge?: boolean;
  serverError?: boolean;
  reason?: string;
}

// ============================================
// CORS HEADERS
// ============================================

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

// ============================================
// UTILITY FUNCTIONS
// ============================================

function generateRequestId(): string {
  return `push_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`;
}

/**
 * Get safe endpoint short for logging (first 20 + last 6 chars)
 */
function getEndpointShort(endpoint: string): string {
  if (!endpoint || endpoint.length < 30) return endpoint;
  return `${endpoint.substring(0, 20)}...${endpoint.substring(endpoint.length - 6)}`;
}

/**
 * Get VAPID public key fingerprint (last 8 chars) for safe logging
 */
function getVapidFingerprint(publicKey: string): string {
  if (!publicKey || publicKey.length < 8) return "INVALID";
  return publicKey.substring(publicKey.length - 8);
}

/**
 * Delay utility for retry logic
 */
function delay(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// ============================================
// VAPID CONFIGURATION
// ============================================

/**
 * Validate VAPID keys at startup
 * - Public key: 65 bytes (uncompressed EC point starting with 0x04)
 * - Private key: 32 bytes (raw EC scalar)
 * 
 * Keys MUST be generated by: npx web-push generate-vapid-keys
 * Format: URL-safe Base64 (no padding, - instead of +, _ instead of /)
 */
function validateAndGetVapidConfig(): { publicKey: string; privateKey: string; subject: string } {
  const publicKey = Deno.env.get("VAPID_PUBLIC_KEY");
  const privateKey = Deno.env.get("VAPID_PRIVATE_KEY");
  const subject = Deno.env.get("VAPID_SUBJECT") || "mailto:admin@roomrise.vn";

  if (!publicKey) {
    throw new Error("[VAPID] VAPID_PUBLIC_KEY not configured. Generate with: npx web-push generate-vapid-keys");
  }
  
  if (!privateKey) {
    throw new Error("[VAPID] VAPID_PRIVATE_KEY not configured. Generate with: npx web-push generate-vapid-keys");
  }

  // Pre-validate key sizes before returning
  // This will catch config errors early
  const publicKeyBytes = urlBase64ToUint8Array(publicKey);
  const privateKeyBytes = urlBase64ToUint8Array(privateKey);
  
  if (privateKeyBytes.length !== 32) {
    const hint = privateKeyBytes.length === 65 
      ? "⚠️ KEYS SWAPPED: Private key has 65 bytes (should be public key). Swap them!"
      : "Generate new keys: npx web-push generate-vapid-keys";
    console.error(`[VAPID] CRITICAL: VAPID_PRIVATE_KEY=${privateKeyBytes.length} bytes (expected 32). ${hint}`);
    console.error(`[VAPID] HINT: Private key should be SHORT (~43 chars), Public key should be LONG (~87 chars)`);
    throw new Error(
      `VAPID_PRIVATE_KEY invalid: ${privateKeyBytes.length} bytes, expected 32. ` +
      `${hint} Update Supabase secrets with correct keys.`
    );
  }
  
  if (publicKeyBytes.length !== 65) {
    const hint = publicKeyBytes.length === 32 
      ? "⚠️ KEYS SWAPPED: Public key has 32 bytes (should be private key). Swap them!"
      : "Generate new keys: npx web-push generate-vapid-keys";
    console.error(`[VAPID] CRITICAL: VAPID_PUBLIC_KEY=${publicKeyBytes.length} bytes (expected 65). ${hint}`);
    throw new Error(
      `VAPID_PUBLIC_KEY invalid: ${publicKeyBytes.length} bytes, expected 65. ` +
      `${hint} Update Supabase secrets with correct keys.`
    );
  }
  
  if (publicKeyBytes[0] !== 0x04) {
    console.error(`[VAPID] CRITICAL: VAPID_PUBLIC_KEY invalid prefix: 0x${publicKeyBytes[0].toString(16)}, expected 0x04`);
    throw new Error(`VAPID_PUBLIC_KEY invalid format: must start with 0x04 (uncompressed EC point)`);
  }

  console.log(`[VAPID] Keys validated - public: ${publicKeyBytes.length} bytes, private: ${privateKeyBytes.length} bytes`);
  
  return { publicKey, privateKey, subject };
}

// ============================================
// VAPID JWT IMPLEMENTATION (FIXED FOR DENO)
// ============================================

/**
 * Convert URL-safe base64 to Uint8Array
 */
function urlBase64ToUint8Array(base64String: string): Uint8Array {
  // Add padding if needed
  let padding = "";
  const remainder = base64String.length % 4;
  if (remainder === 2) padding = "==";
  else if (remainder === 3) padding = "=";
  
  // Convert URL-safe to standard base64
  const base64 = (base64String + padding)
    .replace(/-/g, "+")
    .replace(/_/g, "/");

  const rawData = atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

/**
 * Convert Uint8Array to URL-safe base64
 */
function uint8ArrayToUrlBase64(uint8Array: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < uint8Array.length; i++) {
    binary += String.fromCharCode(uint8Array[i]);
  }
  const base64 = btoa(binary);
  return base64.replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

/**
 * Create VAPID JWT for authorization
 * 
 * VAPID keys from web-push generate-vapid-keys:
 * - Public key: 65 bytes uncompressed EC point (04 || x || y) as URL-safe base64
 * - Private key: 32 bytes raw scalar (d) as URL-safe base64
 * 
 * This implementation correctly imports the keys in JWK format.
 */
async function createVapidJwt(
  audience: string,
  subject: string,
  privateKeyBase64: string,
  publicKeyBase64: string
): Promise<string> {
  // JWT Header
  const header = { alg: "ES256", typ: "JWT" };
  const now = Math.floor(Date.now() / 1000);
  
  // JWT Payload  
  const payload = {
    aud: audience,
    exp: now + 12 * 60 * 60, // 12 hours
    sub: subject,
  };

  // Encode header and payload
  const headerBase64 = uint8ArrayToUrlBase64(
    new TextEncoder().encode(JSON.stringify(header))
  );
  const payloadBase64 = uint8ArrayToUrlBase64(
    new TextEncoder().encode(JSON.stringify(payload))
  );

  const unsignedToken = `${headerBase64}.${payloadBase64}`;

  // Decode keys from URL-safe base64
  const privateKeyBytes = urlBase64ToUint8Array(privateKeyBase64);
  const publicKeyBytes = urlBase64ToUint8Array(publicKeyBase64);
  
  console.log(`[vapid] Private key length: ${privateKeyBytes.length}, Public key length: ${publicKeyBytes.length}`);
  
  // Validate key sizes with detailed error messages
  if (privateKeyBytes.length !== 32) {
    const hint = privateKeyBytes.length === 65 
      ? "ERROR: You likely swapped the keys! Private key should be ~43 chars, Public key ~87 chars."
      : "Generate new keys with: npx web-push generate-vapid-keys";
    throw new Error(
      `Invalid VAPID private key length: ${privateKeyBytes.length} bytes, expected 32 bytes. ` +
      `${hint} Then update Supabase secrets: VAPID_PRIVATE_KEY (short ~43 chars) and VAPID_PUBLIC_KEY (long ~87 chars).`
    );
  }
  
  if (publicKeyBytes.length !== 65) {
    const hint = publicKeyBytes.length === 32 
      ? "ERROR: You likely swapped the keys! Public key should be ~87 chars, Private key ~43 chars."
      : "Generate new keys with: npx web-push generate-vapid-keys";
    throw new Error(
      `Invalid VAPID public key length: ${publicKeyBytes.length} bytes, expected 65 bytes. ` +
      `${hint} Then update Supabase secrets.`
    );
  }
  
  if (publicKeyBytes[0] !== 0x04) {
    throw new Error(`Invalid VAPID public key format: expected 0x04 prefix for uncompressed EC point`);
  }

  // Extract x, y coordinates from public key (skip 0x04 prefix)
  const x = publicKeyBytes.slice(1, 33);  // 32 bytes
  const y = publicKeyBytes.slice(33, 65); // 32 bytes
  const d = privateKeyBytes;               // 32 bytes (private key scalar)

  // Build JWK for ECDSA P-256
  const jwk = {
    kty: "EC",
    crv: "P-256",
    x: uint8ArrayToUrlBase64(x),
    y: uint8ArrayToUrlBase64(y),
    d: uint8ArrayToUrlBase64(d),
  };

  console.log(`[vapid] JWK coords - x length: ${x.length}, y length: ${y.length}, d length: ${d.length}`);
  console.log(`[vapid] JWK base64 - x: ${jwk.x.substring(0, 10)}..., y: ${jwk.y.substring(0, 10)}..., d: ${jwk.d.substring(0, 10)}...`);

  // Import the private key
  const cryptoKey = await crypto.subtle.importKey(
    "jwk",
    jwk,
    { name: "ECDSA", namedCurve: "P-256" },
    false,
    ["sign"]
  );

  console.log("[vapid] Key imported successfully");

  // Sign the token
  const signatureBuffer = await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" },
    cryptoKey,
    new TextEncoder().encode(unsignedToken)
  );

  // Convert signature from DER to JWS format (fixed 64 bytes for ES256)
  const signature = new Uint8Array(signatureBuffer);
  const signatureBase64 = uint8ArrayToUrlBase64(signature);

  return `${unsignedToken}.${signatureBase64}`;
}

// ============================================
// WEB PUSH ENCRYPTION - RFC 8291 / RFC 8188
// ============================================

/**
 * Encrypt push payload using aes128gcm per RFC 8291
 * 
 * This implements the "Web Push Message Encryption" standard.
 * Reference: https://datatracker.ietf.org/doc/html/rfc8291
 */
async function encryptPayload(
  payloadString: string,
  p256dh: string,
  auth: string
): Promise<{ encrypted: Uint8Array; salt: Uint8Array; publicKey: Uint8Array }> {
  const payloadBytes = new TextEncoder().encode(payloadString);

  // 1. Generate ephemeral ECDH key pair for this message
  const localKeyPair = await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" },
    true,
    ["deriveBits"]
  );

  // 2. Export local public key (65 bytes uncompressed: 0x04 + X + Y)
  const localPublicKeyBuffer = await crypto.subtle.exportKey("raw", localKeyPair.publicKey);
  const localPublicKey = new Uint8Array(localPublicKeyBuffer);

  // 3. Import subscriber's public key (ua_public from the subscription)
  const subscriberPublicKeyBytes = urlBase64ToUint8Array(p256dh);
  const subscriberPublicKey = await crypto.subtle.importKey(
    "raw",
    subscriberPublicKeyBytes.buffer as ArrayBuffer,
    { name: "ECDH", namedCurve: "P-256" },
    false,
    []
  );

  // 4. Perform ECDH to get shared secret
  const ecdhSecretBits = await crypto.subtle.deriveBits(
    { name: "ECDH", public: subscriberPublicKey },
    localKeyPair.privateKey,
    256
  );
  const ecdhSecret = new Uint8Array(ecdhSecretBits);

  // 5. Generate 16-byte random salt
  const salt = crypto.getRandomValues(new Uint8Array(16));
  
  // 6. Get auth secret from subscription
  const authSecret = urlBase64ToUint8Array(auth);

  // 7. Derive IKM (Input Keying Material) per RFC 8291 Section 3.3
  // info = "WebPush: info" || 0x00 || ua_public || as_public
  const infoPrefix = new TextEncoder().encode("WebPush: info\0");
  const ikmInfo = new Uint8Array([
    ...infoPrefix,
    ...subscriberPublicKeyBytes,
    ...localPublicKey
  ]);
  
  // IKM = HKDF-Extract(salt=auth_secret, IKM=ecdh_secret)
  // then HKDF-Expand to get 32 bytes
  const ikm = await hkdf(authSecret, ecdhSecret, ikmInfo, 32);

  // 8. Derive Content Encryption Key (CEK) and Nonce per RFC 8188
  // cek_info = "Content-Encoding: aes128gcm" || 0x00
  const cekInfo = new TextEncoder().encode("Content-Encoding: aes128gcm\0");
  const cek = await hkdf(salt, ikm, cekInfo, 16);

  // nonce_info = "Content-Encoding: nonce" || 0x00
  const nonceInfo = new TextEncoder().encode("Content-Encoding: nonce\0");
  const nonce = await hkdf(salt, ikm, nonceInfo, 12);

  // 9. Prepare the plaintext with padding delimiter
  // Per RFC 8291: plaintext = data || 0x02 (delimiter) || padding (zeros)
  // We use minimal padding: just the delimiter byte
  const paddedPayload = new Uint8Array(payloadBytes.length + 1);
  paddedPayload.set(payloadBytes, 0);
  paddedPayload[payloadBytes.length] = 0x02; // Record delimiter

  // 10. Encrypt with AES-128-GCM
  const encryptionKey = await crypto.subtle.importKey(
    "raw",
    cek.buffer as ArrayBuffer,
    { name: "AES-GCM" },
    false,
    ["encrypt"]
  );

  const ciphertext = new Uint8Array(
    await crypto.subtle.encrypt(
      { name: "AES-GCM", iv: nonce.buffer as ArrayBuffer, tagLength: 128 },
      encryptionKey,
      paddedPayload
    )
  );

  console.log(`[encrypt] Payload: ${payloadBytes.length}b, Ciphertext: ${ciphertext.length}b, Salt: ${salt.length}b, Key: ${localPublicKey.length}b`);

  return { encrypted: ciphertext, salt, publicKey: localPublicKey };
}

/**
 * HKDF (HMAC-based Key Derivation Function) per RFC 5869
 * Simplified for Web Push: single extract + expand operation
 */
async function hkdf(
  salt: Uint8Array,
  ikm: Uint8Array,
  info: Uint8Array,
  length: number
): Promise<Uint8Array> {
  // Extract: PRK = HMAC-SHA256(salt, IKM)
  const extractKey = await crypto.subtle.importKey(
    "raw",
    salt.buffer as ArrayBuffer,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const prk = new Uint8Array(
    await crypto.subtle.sign("HMAC", extractKey, ikm.buffer as ArrayBuffer)
  );

  // Expand: OKM = HMAC-SHA256(PRK, info || 0x01) truncated to length
  const expandKey = await crypto.subtle.importKey(
    "raw",
    prk,
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  
  const expandData = new Uint8Array([...info, 0x01]);
  const okm = new Uint8Array(
    await crypto.subtle.sign("HMAC", expandKey, expandData)
  );

  return okm.slice(0, length);
}

// ============================================
// SEND WEB PUSH WITH RETRY
// ============================================

async function sendWebPush(
  subscription: PushSubscription,
  payload: Record<string, unknown>,
  vapidConfig: { publicKey: string; privateKey: string; subject: string },
  requestId: string,
  retryCount = 0
): Promise<PushSendResult> {
  const endpointUrl = new URL(subscription.endpoint);
  const endpointHost = endpointUrl.host;
  const endpointShort = getEndpointShort(subscription.endpoint);
  const isApplePush = endpointHost.includes('apple.com');
  const ttl = "60"; // 60 seconds for test, 86400 for production
  const timestamp = new Date().toISOString();

  console.log(`[send-push][${requestId}] Sending to: ${endpointShort}, isApple: ${isApplePush}, retry: ${retryCount}`);

  try {
    const audience = `${endpointUrl.protocol}//${endpointUrl.host}`;

    // Create VAPID JWT
    const jwt = await createVapidJwt(
      audience,
      vapidConfig.subject,
      vapidConfig.privateKey,
      vapidConfig.publicKey
    );

    console.log(`[send-push][${requestId}] VAPID JWT created, length: ${jwt.length}`);

    let response: Response;

    // ALL push services (including Apple) require aes128gcm encryption
    // The assumption that Apple uses plain JSON was WRONG
    // Apple's Web Push (via web.push.apple.com) uses the same RFC 8291 standard
    const payloadString = JSON.stringify(payload);
    
    // Check payload size before encryption
    const payloadBytes = new TextEncoder().encode(payloadString);
    if (payloadBytes.length > 4000) { // Leave room for encryption overhead
      console.error(`[send-push][${requestId}] Payload too large: ${payloadBytes.length} bytes`);
      return {
        success: false,
        statusCode: 413,
        error: "PAYLOAD_TOO_LARGE",
        payloadTooLarge: true,
        reason: "PAYLOAD_TOO_LARGE",
      };
    }

    console.log(`[send-push][${requestId}] Encrypting payload (${payloadBytes.length} bytes) for ${isApplePush ? 'Apple' : 'Chrome/Firefox'}`);

    const { encrypted, salt, publicKey } = await encryptPayload(
      payloadString,
      subscription.p256dh,
      subscription.auth
    );

    // Build aes128gcm body per RFC 8188
    // Format: salt (16) + rs (4) + idlen (1) + keyid (65) + ciphertext
    const body = new Uint8Array([
      ...salt,                    // 16 bytes salt
      0, 0, 0x10, 0,              // 4 bytes record size (4096 = 0x1000)
      65,                         // 1 byte key id length
      ...publicKey,               // 65 bytes server public key
      ...encrypted,               // ciphertext
    ]);

    console.log(`[send-push][${requestId}] Encrypted body size: ${body.length} bytes`);

    response = await fetch(subscription.endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/octet-stream",
        "Content-Encoding": "aes128gcm",
        "Content-Length": body.length.toString(),
        "Authorization": `vapid t=${jwt}, k=${vapidConfig.publicKey}`,
        "TTL": ttl,
        "Urgency": "high",
      },
      body,
    });

    const statusCode = response.status;
    console.log(`[send-push][${requestId}] Response status: ${statusCode}`);

    // SUCCESS (201 Created)
    if (response.ok || statusCode === 201) {
      console.log(`[send-push][${requestId}] ✓ SENT OK to ${endpointShort}`);
      return { success: true, statusCode, reason: "SENT_OK" };
    }

    const errorBody = await response.text();
    console.error(`[send-push][${requestId}] ✗ FAILED: status=${statusCode}, body=${errorBody?.substring(0, 200)}`);

    // CATEGORIZE ERROR BY STATUS CODE

    // 404/410: Subscription expired/invalid - AUTO-CLEAN
    if (statusCode === 404 || statusCode === 410) {
      console.warn(`[send-push][${requestId}] SUBSCRIPTION_GONE: ${endpointShort}`);
      return {
        success: false,
        statusCode,
        error: "SUBSCRIPTION_EXPIRED",
        errorBody: errorBody?.substring(0, 200),
        needResubscribe: true,
        reason: "SUBSCRIPTION_GONE",
      };
    }

    // 401/403: VAPID authorization issue - DO NOT auto-delete
    if (statusCode === 401 || statusCode === 403) {
      console.error(`[send-push][${requestId}] VAPID_UNAUTHORIZED: ${errorBody}`);
      return {
        success: false,
        statusCode,
        error: "VAPID_UNAUTHORIZED",
        errorBody: errorBody?.substring(0, 200),
        vapidMismatch: true,
        reason: "VAPID_UNAUTHORIZED",
      };
    }

    // 400: Bad request - payload/headers issue
    if (statusCode === 400) {
      console.error(`[send-push][${requestId}] BAD_REQUEST: ${errorBody}`);
      return {
        success: false,
        statusCode,
        error: "BAD_REQUEST",
        errorBody: errorBody?.substring(0, 500),
        badRequest: true,
        reason: "BAD_REQUEST",
      };
    }

    // 413: Payload too large
    if (statusCode === 413) {
      console.error(`[send-push][${requestId}] PAYLOAD_TOO_LARGE`);
      return {
        success: false,
        statusCode,
        error: "PAYLOAD_TOO_LARGE",
        payloadTooLarge: true,
        reason: "PAYLOAD_TOO_LARGE",
      };
    }

    // 429/5xx: Rate limit or server error - RETRY ONCE with backoff
    if ((statusCode === 429 || statusCode >= 500) && retryCount < 1) {
      console.warn(`[send-push][${requestId}] SERVER_ERROR ${statusCode}, retrying in 500ms...`);
      await delay(500);
      return sendWebPush(subscription, payload, vapidConfig, requestId, retryCount + 1);
    }

    if (statusCode === 429 || statusCode >= 500) {
      console.error(`[send-push][${requestId}] SERVER_ERROR after retry: ${statusCode}`);
      return {
        success: false,
        statusCode,
        error: `SERVER_ERROR_${statusCode}`,
        errorBody: errorBody?.substring(0, 200),
        serverError: true,
        reason: `SERVER_ERROR_${statusCode}`,
      };
    }

    // Other error
    return {
      success: false,
      statusCode,
      error: errorBody || `HTTP_${statusCode}`,
      errorBody: errorBody?.substring(0, 200),
      reason: `HTTP_${statusCode}`,
    };

  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : "Unknown error";
    const errorStack = error instanceof Error ? error.stack?.substring(0, 500) : "";
    
    console.error(`[send-push][${requestId}] Push send error:`, error);
    console.error(`[send-push][${requestId}] Stack:`, errorStack);
    
    return {
      success: false,
      error: errorMsg,
      reason: "NETWORK_OR_CRYPTO_ERROR",
      errorBody: errorStack,
    };
  }
}

// ============================================
// MAIN HANDLER
// ============================================

serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  const requestId = generateRequestId();
  const failures: FailureDetail[] = [];

  try {
    const body: SendPushRequest = await req.json();
    const {
      event_type,
      idempotency_key,
      recipient_user_ids,
      assigned_to_user_id,
      use_triage_group,
      broadcast_all,
      payload,
      source_table,
      source_record_id,
      debug,
    } = body;

    // Validate required fields
    if (!event_type || !idempotency_key || !payload?.title) {
      return new Response(
        JSON.stringify({
          success: false,
          error: "Missing required fields: event_type, idempotency_key, payload.title",
          requestId,
        }),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    console.log(`[send-push][${requestId}] Processing ${event_type} with key: ${idempotency_key}`);

    // Get and validate VAPID config
    let vapidConfig;
    try {
      vapidConfig = validateAndGetVapidConfig();
      console.log(`[send-push][${requestId}] VAPID validated: fingerprint=...${getVapidFingerprint(vapidConfig.publicKey)}, subject=${vapidConfig.subject}`);
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : "Unknown error";
      console.error(`[send-push][${requestId}] VAPID validation failed:`, errorMsg);
      return new Response(
        JSON.stringify({
          success: false,
          error: "Push notifications not configured (VAPID keys invalid or missing)",
          details: errorMsg,
          hint: "Generate new keys with: npx web-push generate-vapid-keys",
          requestId,
        }),
        {
          status: 503,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    // Create service client
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const serviceClient = createClient(supabaseUrl, supabaseServiceKey);

    // Determine recipients
    let targetUserIds: string[] = [];
    let getAllSubscriptions = false;

    if (broadcast_all) {
      getAllSubscriptions = true;
      console.log(`[send-push][${requestId}] Mode: broadcast_all`);
    } else if (recipient_user_ids && recipient_user_ids.length > 0) {
      targetUserIds = recipient_user_ids;
      console.log(`[send-push][${requestId}] Mode: explicit recipients (${targetUserIds.length} users)`);
    } else if (assigned_to_user_id) {
      targetUserIds = [assigned_to_user_id];
      console.log(`[send-push][${requestId}] Mode: assigned_to_user`);
    } else if (use_triage_group) {
      const triageRole = Deno.env.get("TRIAGE_ROLE") || "cskh";
      const { data: triageUsers, error: triageError } = await serviceClient
        .from("user_roles")
        .select("user_id")
        .eq("role", triageRole);

      if (triageError) {
        console.error(`[send-push][${requestId}] Failed to get triage team:`, triageError);
      } else if (triageUsers && triageUsers.length > 0) {
        targetUserIds = triageUsers.map((u) => u.user_id);
        console.log(`[send-push][${requestId}] Mode: triage_group (${targetUserIds.length} users)`);
      } else {
        getAllSubscriptions = true;
        console.log(`[send-push][${requestId}] Mode: triage fallback to broadcast_all`);
      }
    }

    if (!getAllSubscriptions && targetUserIds.length === 0) {
      console.log(`[send-push][${requestId}] No recipients found`);
      return new Response(
        JSON.stringify({
          success: true,
          sent: 0,
          failed: 0,
          total: 0,
          message: "No recipients found",
          requestId,
          failures: [],
        }),
        {
          status: 200,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    // Get subscriptions
    let subscriptions: PushSubscription[] = [];
    let subError;

    if (getAllSubscriptions) {
      const result = await serviceClient
        .from("push_subscriptions")
        .select("user_id, id:id, endpoint, p256dh, auth")
        .eq("is_active", true)
        .or("consecutive_failures.lt.3,consecutive_failures.is.null");

      subscriptions = (result.data || []).map((s) => ({
        user_id: s.user_id,
        subscription_id: s.id,
        endpoint: s.endpoint,
        p256dh: s.p256dh,
        auth: s.auth,
      }));
      subError = result.error;
    } else {
      const result = await serviceClient.rpc("get_users_push_subscriptions", {
        p_user_ids: targetUserIds,
      });
      subscriptions = result.data || [];
      subError = result.error;
    }

    if (subError) {
      console.error(`[send-push][${requestId}] Failed to get subscriptions:`, subError);
      return new Response(
        JSON.stringify({
          success: false,
          error: "Failed to get subscriptions",
          requestId,
        }),
        {
          status: 500,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    if (subscriptions.length === 0) {
      console.log(`[send-push][${requestId}] No active subscriptions found`);
      return new Response(
        JSON.stringify({
          success: true,
          sent: 0,
          failed: 0,
          total: 0,
          duplicates: 0,
          expired: 0,
          message: "No active push subscriptions",
          requestId,
          failures: [],
        }),
        {
          status: 200,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    console.log(`[send-push][${requestId}] Found ${subscriptions.length} subscriptions`);

    // Results counters
    const results = {
      sent: 0,
      duplicates: 0,
      failed: 0,
      expired: 0,
    };

    // Build minimal push payload
    const pushPayload = {
      title: payload.title,
      body: payload.body,
      icon: payload.icon || "/favicon.png",
      badge: payload.badge || "/favicon.png",
      tag: payload.tag || `${event_type}-${Date.now()}`,
      data: {
        type: event_type,
        ts: Date.now(),
        entity_id: payload.entity_id,
        deep_link: payload.deep_link,
        ...payload.data,
      },
    };

    // Send to each subscription
    for (const sub of subscriptions) {
      const endpointShort = getEndpointShort(sub.endpoint);

      // Check idempotency
      const { data: deliveryResult, error: deliveryError } =
        await serviceClient.rpc("try_record_push_delivery", {
          p_event_type: event_type,
          p_idempotency_key: idempotency_key,
          p_recipient_user_id: sub.user_id,
          p_subscription_id: sub.subscription_id,
          p_source_table: source_table || null,
          p_source_record_id: source_record_id || null,
          p_payload_hash: null,
        });

      if (deliveryError) {
        console.error(`[send-push][${requestId}] Delivery record error:`, deliveryError);
        results.failed++;
        failures.push({
          endpointShort,
          userId: sub.user_id.substring(0, 8),
          statusCode: null,
          reason: "DELIVERY_RECORD_ERROR",
          bodySnippet: deliveryError.message,
          timestamp: new Date().toISOString(),
        });
        continue;
      }

      if (deliveryResult === "DUPLICATE") {
        console.log(`[send-push][${requestId}] Duplicate for user ${sub.user_id.substring(0, 8)}`);
        results.duplicates++;
        continue;
      }

      // Send push
      const pushResult = await sendWebPush(sub, pushPayload, vapidConfig, requestId);

      if (pushResult.success) {
        results.sent++;
        // Mark success
        await serviceClient.rpc("mark_push_subscription_success", {
          p_subscription_id: sub.subscription_id,
        });
        console.log(`[send-push][${requestId}] ✓ Sent to ${sub.user_id.substring(0, 8)} via ${endpointShort}`);

      } else if (pushResult.needResubscribe) {
        // 404/410 - AUTO-CLEAN
        results.expired++;
        
        await serviceClient
          .from("push_subscriptions")
          .update({
            is_active: false,
            last_failure_reason: pushResult.reason || "SUBSCRIPTION_GONE",
            last_failure_at: new Date().toISOString(),
          })
          .eq("id", sub.subscription_id);

        console.warn(`[send-push][${requestId}] AUTO-CLEAN: Deactivated ${endpointShort} (${pushResult.reason})`);

        failures.push({
          endpointShort,
          userId: sub.user_id.substring(0, 8),
          statusCode: pushResult.statusCode || null,
          reason: pushResult.reason || "SUBSCRIPTION_GONE",
          bodySnippet: pushResult.errorBody || null,
          timestamp: new Date().toISOString(),
        });

      } else if (pushResult.vapidMismatch) {
        // 401/403 - VAPID issue, log but don't delete
        results.failed++;

        await serviceClient.rpc("mark_push_subscription_failure", {
          p_subscription_id: sub.subscription_id,
          p_reason: `VAPID_MISMATCH_${pushResult.statusCode}`,
        });

        console.error(`[send-push][${requestId}] VAPID_MISMATCH: ${endpointShort}`);

        failures.push({
          endpointShort,
          userId: sub.user_id.substring(0, 8),
          statusCode: pushResult.statusCode || null,
          reason: "VAPID_UNAUTHORIZED",
          bodySnippet: pushResult.errorBody || null,
          timestamp: new Date().toISOString(),
        });

      } else {
        // Other error
        results.failed++;

        await serviceClient.rpc("mark_push_subscription_failure", {
          p_subscription_id: sub.subscription_id,
          p_reason: pushResult.error || "Unknown error",
        });

        failures.push({
          endpointShort,
          userId: sub.user_id.substring(0, 8),
          statusCode: pushResult.statusCode || null,
          reason: pushResult.reason || pushResult.error || "UNKNOWN_ERROR",
          bodySnippet: pushResult.errorBody || null,
          timestamp: new Date().toISOString(),
        });
      }
    }

    console.log(`[send-push][${requestId}] Results: sent=${results.sent}, failed=${results.failed}, expired=${results.expired}, duplicates=${results.duplicates}`);

    // Build response
    const response: Record<string, unknown> = {
      success: true,
      requestId,
      total: subscriptions.length,
      sent: results.sent,
      failed: results.failed,
      expired: results.expired,
      duplicates: results.duplicates,
      // Return up to 3 failure details for debugging
      failures: failures.slice(0, 3),
    };

    if (results.expired > 0) {
      response.needResubscribe = true;
    }

    if (debug) {
      response.vapidFingerprint = getVapidFingerprint(vapidConfig.publicKey);
      response.vapidSubject = vapidConfig.subject;
    }

    return new Response(JSON.stringify(response), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (error) {
    console.error(`[send-push][${requestId}] Error:`, error);
    return new Response(
      JSON.stringify({
        success: false,
        error: "Internal server error",
        details: error instanceof Error ? error.message : "Unknown error",
        stack: error instanceof Error ? error.stack?.substring(0, 500) : null,
        requestId,
        failures,
      }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
